import type {
  WidgetType,
  WidgetCategory,
  ScreenProfile,
  Widget,
} from '../types/layout';

// =============================================================================
// WIDGET DEFINITION INTERFACE
// =============================================================================

export interface WidgetDefinition {
  type: WidgetType;
  label: string;
  shortLabel: string;
  description: string;
  category: WidgetCategory;
  unit: string;
  unitImperial?: string;
  minWidth: number;
  minHeight: number;
  defaultWidth: number;
  defaultHeight: number;
  requiresSensor?: boolean;
  sensorType?: string;
  requiresGPS?: boolean;
  requiresRoute?: boolean;
  supportsZones?: boolean;
  supportsGraph?: boolean;
  icon: string;
}

// =============================================================================
// CATEGORY METADATA
// =============================================================================

export interface CategoryDefinition {
  id: WidgetCategory;
  label: string;
  description: string;
  icon: string;
  color: string;
}

export const WIDGET_CATEGORIES: CategoryDefinition[] = [
  {
    id: 'speed',
    label: 'Speed',
    description: 'Current, average, and lap speed metrics',
    icon: 'speedometer',
    color: '#3b82f6',
  },
  {
    id: 'power',
    label: 'Power',
    description: 'Power output, zones, and training metrics',
    icon: 'flash',
    color: '#f59e0b',
  },
  {
    id: 'heart_rate',
    label: 'Heart Rate',
    description: 'Heart rate and cardiovascular metrics',
    icon: 'heart',
    color: '#ef4444',
  },
  {
    id: 'cadence',
    label: 'Cadence',
    description: 'Pedaling cadence metrics',
    icon: 'refresh',
    color: '#8b5cf6',
  },
  {
    id: 'distance',
    label: 'Distance',
    description: 'Distance traveled and remaining',
    icon: 'map-pin',
    color: '#10b981',
  },
  {
    id: 'time',
    label: 'Time',
    description: 'Elapsed time, lap time, and clock',
    icon: 'clock',
    color: '#6366f1',
  },
  {
    id: 'elevation',
    label: 'Elevation',
    description: 'Altitude, climbing, and grade metrics',
    icon: 'trending-up',
    color: '#84cc16',
  },
  {
    id: 'navigation',
    label: 'Navigation',
    description: 'Turn-by-turn and route guidance',
    icon: 'navigation',
    color: '#06b6d4',
  },
  {
    id: 'performance',
    label: 'Performance',
    description: 'Training load, TSS, and fitness metrics',
    icon: 'activity',
    color: '#ec4899',
  },
  {
    id: 'gears',
    label: 'Gears',
    description: 'Electronic shifting and gear info',
    icon: 'settings',
    color: '#78716c',
  },
  {
    id: 'environment',
    label: 'Environment',
    description: 'Weather, temperature, and battery',
    icon: 'sun',
    color: '#0ea5e9',
  },
  {
    id: 'graphs',
    label: 'Graphs',
    description: 'Visual data trends and charts',
    icon: 'bar-chart',
    color: '#a855f7',
  },
  {
    id: 'maps',
    label: 'Maps',
    description: 'Map views and route profiles',
    icon: 'map',
    color: '#22c55e',
  },
];

// =============================================================================
// COMPLETE WIDGET LIBRARY
// =============================================================================

export const WIDGET_DEFINITIONS: Record<WidgetType, WidgetDefinition> = {
  // ---------------------------------------------------------------------------
  // SPEED WIDGETS
  // ---------------------------------------------------------------------------
  speed: {
    type: 'speed',
    label: 'Speed',
    shortLabel: 'Speed',
    description: 'Current speed from GPS or speed sensor',
    category: 'speed',
    unit: 'km/h',
    unitImperial: 'mph',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'speedometer',
  },
  speed_avg: {
    type: 'speed_avg',
    label: 'Average Speed',
    shortLabel: 'Avg Spd',
    description: 'Average speed for the current activity',
    category: 'speed',
    unit: 'km/h',
    unitImperial: 'mph',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'speedometer',
  },
  speed_max: {
    type: 'speed_max',
    label: 'Max Speed',
    shortLabel: 'Max Spd',
    description: 'Maximum speed reached during the activity',
    category: 'speed',
    unit: 'km/h',
    unitImperial: 'mph',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'speedometer',
  },
  speed_lap: {
    type: 'speed_lap',
    label: 'Lap Speed',
    shortLabel: 'Lap Spd',
    description: 'Average speed for the current lap',
    category: 'speed',
    unit: 'km/h',
    unitImperial: 'mph',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'speedometer',
  },
  speed_last_lap: {
    type: 'speed_last_lap',
    label: 'Last Lap Speed',
    shortLabel: 'Lst Lap',
    description: 'Average speed for the previous lap',
    category: 'speed',
    unit: 'km/h',
    unitImperial: 'mph',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'speedometer',
  },
  speed_3s: {
    type: 'speed_3s',
    label: '3s Avg Speed',
    shortLabel: '3s Spd',
    description: '3-second rolling average speed',
    category: 'speed',
    unit: 'km/h',
    unitImperial: 'mph',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'speedometer',
  },
  pace: {
    type: 'pace',
    label: 'Pace',
    shortLabel: 'Pace',
    description: 'Current pace (time per distance unit)',
    category: 'speed',
    unit: 'min/km',
    unitImperial: 'min/mi',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'speedometer',
  },
  pace_avg: {
    type: 'pace_avg',
    label: 'Average Pace',
    shortLabel: 'Avg Pace',
    description: 'Average pace for the activity',
    category: 'speed',
    unit: 'min/km',
    unitImperial: 'min/mi',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'speedometer',
  },

  // ---------------------------------------------------------------------------
  // POWER WIDGETS
  // ---------------------------------------------------------------------------
  power: {
    type: 'power',
    label: 'Power',
    shortLabel: 'Power',
    description: 'Current power output',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    supportsZones: true,
    icon: 'flash',
  },
  power_3s: {
    type: 'power_3s',
    label: '3s Power',
    shortLabel: '3s Pwr',
    description: '3-second smoothed power for responsive display',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    supportsZones: true,
    icon: 'flash',
  },
  power_10s: {
    type: 'power_10s',
    label: '10s Power',
    shortLabel: '10s Pwr',
    description: '10-second rolling average power',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    supportsZones: true,
    icon: 'flash',
  },
  power_30s: {
    type: 'power_30s',
    label: '30s Power',
    shortLabel: '30s Pwr',
    description: '30-second rolling average power',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    supportsZones: true,
    icon: 'flash',
  },
  power_avg: {
    type: 'power_avg',
    label: 'Average Power',
    shortLabel: 'Avg Pwr',
    description: 'Average power for the activity',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  power_max: {
    type: 'power_max',
    label: 'Max Power',
    shortLabel: 'Max Pwr',
    description: 'Maximum power reached during activity',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  power_lap: {
    type: 'power_lap',
    label: 'Lap Power',
    shortLabel: 'Lap Pwr',
    description: 'Average power for current lap',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  power_last_lap: {
    type: 'power_last_lap',
    label: 'Last Lap Power',
    shortLabel: 'Lst Pwr',
    description: 'Average power for previous lap',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  power_normalized: {
    type: 'power_normalized',
    label: 'Normalized Power',
    shortLabel: 'NP',
    description: 'Normalized Power (NP) for variable efforts',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  power_weighted_avg: {
    type: 'power_weighted_avg',
    label: 'Weighted Avg Power',
    shortLabel: 'Wt Avg',
    description: 'Weighted average power accounting for variability',
    category: 'power',
    unit: 'W',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  power_balance: {
    type: 'power_balance',
    label: 'L/R Balance',
    shortLabel: 'Balance',
    description: 'Left/right power balance percentage',
    category: 'power',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 2,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  power_per_kg: {
    type: 'power_per_kg',
    label: 'Power/Weight',
    shortLabel: 'W/kg',
    description: 'Power relative to body weight',
    category: 'power',
    unit: 'W/kg',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  power_ftp_percent: {
    type: 'power_ftp_percent',
    label: '% of FTP',
    shortLabel: '%FTP',
    description: 'Current power as percentage of FTP',
    category: 'power',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    supportsZones: true,
    icon: 'flash',
  },
  power_zone: {
    type: 'power_zone',
    label: 'Power Zone',
    shortLabel: 'P Zone',
    description: 'Current power training zone',
    category: 'power',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    supportsZones: true,
    icon: 'flash',
  },
  power_if: {
    type: 'power_if',
    label: 'Intensity Factor',
    shortLabel: 'IF',
    description: 'Intensity Factor (NP / FTP)',
    category: 'power',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  torque: {
    type: 'torque',
    label: 'Torque',
    shortLabel: 'Torque',
    description: 'Current pedal torque',
    category: 'power',
    unit: 'Nm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  pedal_smoothness: {
    type: 'pedal_smoothness',
    label: 'Pedal Smoothness',
    shortLabel: 'Smooth',
    description: 'Pedaling smoothness percentage',
    category: 'power',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },
  torque_effectiveness: {
    type: 'torque_effectiveness',
    label: 'Torque Effectiveness',
    shortLabel: 'TE',
    description: 'Torque effectiveness percentage',
    category: 'power',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'flash',
  },

  // ---------------------------------------------------------------------------
  // HEART RATE WIDGETS
  // ---------------------------------------------------------------------------
  heart_rate: {
    type: 'heart_rate',
    label: 'Heart Rate',
    shortLabel: 'HR',
    description: 'Current heart rate',
    category: 'heart_rate',
    unit: 'bpm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    supportsZones: true,
    icon: 'heart',
  },
  heart_rate_avg: {
    type: 'heart_rate_avg',
    label: 'Average HR',
    shortLabel: 'Avg HR',
    description: 'Average heart rate for the activity',
    category: 'heart_rate',
    unit: 'bpm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    icon: 'heart',
  },
  heart_rate_max: {
    type: 'heart_rate_max',
    label: 'Max HR',
    shortLabel: 'Max HR',
    description: 'Maximum heart rate reached during activity',
    category: 'heart_rate',
    unit: 'bpm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    icon: 'heart',
  },
  heart_rate_lap: {
    type: 'heart_rate_lap',
    label: 'Lap HR',
    shortLabel: 'Lap HR',
    description: 'Average heart rate for current lap',
    category: 'heart_rate',
    unit: 'bpm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    icon: 'heart',
  },
  heart_rate_last_lap: {
    type: 'heart_rate_last_lap',
    label: 'Last Lap HR',
    shortLabel: 'Lst HR',
    description: 'Average heart rate for previous lap',
    category: 'heart_rate',
    unit: 'bpm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    icon: 'heart',
  },
  heart_rate_zone: {
    type: 'heart_rate_zone',
    label: 'HR Zone',
    shortLabel: 'HR Zone',
    description: 'Current heart rate training zone',
    category: 'heart_rate',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    supportsZones: true,
    icon: 'heart',
  },
  heart_rate_percent_max: {
    type: 'heart_rate_percent_max',
    label: '% Max HR',
    shortLabel: '%Max',
    description: 'Current HR as percentage of max heart rate',
    category: 'heart_rate',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    supportsZones: true,
    icon: 'heart',
  },
  heart_rate_percent_hrr: {
    type: 'heart_rate_percent_hrr',
    label: '% HRR',
    shortLabel: '%HRR',
    description: 'Heart rate as percentage of heart rate reserve',
    category: 'heart_rate',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    supportsZones: true,
    icon: 'heart',
  },
  heart_rate_graph: {
    type: 'heart_rate_graph',
    label: 'HR Trend',
    shortLabel: 'HR Graph',
    description: 'Heart rate trend graph over time',
    category: 'heart_rate',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 3,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    supportsGraph: true,
    icon: 'heart',
  },

  // ---------------------------------------------------------------------------
  // CADENCE WIDGETS
  // ---------------------------------------------------------------------------
  cadence: {
    type: 'cadence',
    label: 'Cadence',
    shortLabel: 'Cad',
    description: 'Current pedaling cadence',
    category: 'cadence',
    unit: 'rpm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'cadence',
    icon: 'refresh',
  },
  cadence_avg: {
    type: 'cadence_avg',
    label: 'Average Cadence',
    shortLabel: 'Avg Cad',
    description: 'Average cadence for the activity',
    category: 'cadence',
    unit: 'rpm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'cadence',
    icon: 'refresh',
  },
  cadence_max: {
    type: 'cadence_max',
    label: 'Max Cadence',
    shortLabel: 'Max Cad',
    description: 'Maximum cadence reached during activity',
    category: 'cadence',
    unit: 'rpm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'cadence',
    icon: 'refresh',
  },
  cadence_lap: {
    type: 'cadence_lap',
    label: 'Lap Cadence',
    shortLabel: 'Lap Cad',
    description: 'Average cadence for current lap',
    category: 'cadence',
    unit: 'rpm',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'cadence',
    icon: 'refresh',
  },

  // ---------------------------------------------------------------------------
  // DISTANCE WIDGETS
  // ---------------------------------------------------------------------------
  distance: {
    type: 'distance',
    label: 'Distance',
    shortLabel: 'Dist',
    description: 'Total distance traveled',
    category: 'distance',
    unit: 'km',
    unitImperial: 'mi',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'map-pin',
  },
  distance_lap: {
    type: 'distance_lap',
    label: 'Lap Distance',
    shortLabel: 'Lap Dist',
    description: 'Distance for current lap',
    category: 'distance',
    unit: 'km',
    unitImperial: 'mi',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'map-pin',
  },
  distance_last_lap: {
    type: 'distance_last_lap',
    label: 'Last Lap Distance',
    shortLabel: 'Lst Dist',
    description: 'Distance for previous lap',
    category: 'distance',
    unit: 'km',
    unitImperial: 'mi',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'map-pin',
  },
  distance_remaining: {
    type: 'distance_remaining',
    label: 'Distance Remaining',
    shortLabel: 'Dist Rem',
    description: 'Distance remaining on route',
    category: 'distance',
    unit: 'km',
    unitImperial: 'mi',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'map-pin',
  },
  distance_to_destination: {
    type: 'distance_to_destination',
    label: 'To Destination',
    shortLabel: 'To Dest',
    description: 'Distance to destination',
    category: 'distance',
    unit: 'km',
    unitImperial: 'mi',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'map-pin',
  },
  odometer: {
    type: 'odometer',
    label: 'Odometer',
    shortLabel: 'Odo',
    description: 'Cumulative total distance',
    category: 'distance',
    unit: 'km',
    unitImperial: 'mi',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'map-pin',
  },

  // ---------------------------------------------------------------------------
  // TIME WIDGETS
  // ---------------------------------------------------------------------------
  time_elapsed: {
    type: 'time_elapsed',
    label: 'Elapsed Time',
    shortLabel: 'Time',
    description: 'Total elapsed time',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 2,
    defaultHeight: 1,
    icon: 'clock',
  },
  time_lap: {
    type: 'time_lap',
    label: 'Lap Time',
    shortLabel: 'Lap',
    description: 'Time for current lap',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'clock',
  },
  time_last_lap: {
    type: 'time_last_lap',
    label: 'Last Lap Time',
    shortLabel: 'Lst Lap',
    description: 'Time for previous lap',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'clock',
  },
  time_avg_lap: {
    type: 'time_avg_lap',
    label: 'Avg Lap Time',
    shortLabel: 'Avg Lap',
    description: 'Average lap time',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'clock',
  },
  time_moving: {
    type: 'time_moving',
    label: 'Moving Time',
    shortLabel: 'Moving',
    description: 'Time spent moving',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 2,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'clock',
  },
  time_stopped: {
    type: 'time_stopped',
    label: 'Stopped Time',
    shortLabel: 'Stopped',
    description: 'Time spent stopped',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'clock',
  },
  time_of_day: {
    type: 'time_of_day',
    label: 'Clock',
    shortLabel: 'Clock',
    description: 'Current time of day',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'clock',
  },
  time_eta: {
    type: 'time_eta',
    label: 'ETA',
    shortLabel: 'ETA',
    description: 'Estimated time of arrival',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'clock',
  },
  time_remaining: {
    type: 'time_remaining',
    label: 'Time Remaining',
    shortLabel: 'Remain',
    description: 'Estimated time remaining',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'clock',
  },
  time_to_destination: {
    type: 'time_to_destination',
    label: 'Time to Destination',
    shortLabel: 'To Dest',
    description: 'Time to reach destination',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'clock',
  },
  time_sunrise: {
    type: 'time_sunrise',
    label: 'Sunrise',
    shortLabel: 'Sunrise',
    description: 'Time of sunrise',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'clock',
  },
  time_sunset: {
    type: 'time_sunset',
    label: 'Sunset',
    shortLabel: 'Sunset',
    description: 'Time of sunset',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'clock',
  },
  laps: {
    type: 'laps',
    label: 'Laps',
    shortLabel: 'Laps',
    description: 'Number of laps completed',
    category: 'time',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'clock',
  },

  // ---------------------------------------------------------------------------
  // ELEVATION WIDGETS
  // ---------------------------------------------------------------------------
  elevation: {
    type: 'elevation',
    label: 'Elevation',
    shortLabel: 'Elev',
    description: 'Current altitude',
    category: 'elevation',
    unit: 'm',
    unitImperial: 'ft',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  elevation_gain: {
    type: 'elevation_gain',
    label: 'Total Ascent',
    shortLabel: 'Ascent',
    description: 'Total elevation gained',
    category: 'elevation',
    unit: 'm',
    unitImperial: 'ft',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  elevation_loss: {
    type: 'elevation_loss',
    label: 'Total Descent',
    shortLabel: 'Descent',
    description: 'Total elevation lost',
    category: 'elevation',
    unit: 'm',
    unitImperial: 'ft',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  elevation_lap_gain: {
    type: 'elevation_lap_gain',
    label: 'Lap Ascent',
    shortLabel: 'Lap Asc',
    description: 'Elevation gained in current lap',
    category: 'elevation',
    unit: 'm',
    unitImperial: 'ft',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  elevation_lap_loss: {
    type: 'elevation_lap_loss',
    label: 'Lap Descent',
    shortLabel: 'Lap Desc',
    description: 'Elevation lost in current lap',
    category: 'elevation',
    unit: 'm',
    unitImperial: 'ft',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  elevation_remaining: {
    type: 'elevation_remaining',
    label: 'Ascent Remaining',
    shortLabel: 'Asc Rem',
    description: 'Climbing remaining on route',
    category: 'elevation',
    unit: 'm',
    unitImperial: 'ft',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'trending-up',
  },
  grade: {
    type: 'grade',
    label: 'Grade',
    shortLabel: 'Grade',
    description: 'Current gradient/slope percentage',
    category: 'elevation',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  grade_avg: {
    type: 'grade_avg',
    label: 'Avg Grade',
    shortLabel: 'Avg Grd',
    description: 'Average gradient for climbing section',
    category: 'elevation',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  grade_max: {
    type: 'grade_max',
    label: 'Max Grade',
    shortLabel: 'Max Grd',
    description: 'Maximum gradient encountered',
    category: 'elevation',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  vam: {
    type: 'vam',
    label: 'VAM',
    shortLabel: 'VAM',
    description: 'Average ascent velocity (m/hr)',
    category: 'elevation',
    unit: 'm/h',
    unitImperial: 'ft/h',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  vam_30s: {
    type: 'vam_30s',
    label: '30s VAM',
    shortLabel: '30s VAM',
    description: '30-second rolling VAM',
    category: 'elevation',
    unit: 'm/h',
    unitImperial: 'ft/h',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },
  vam_lap: {
    type: 'vam_lap',
    label: 'Lap VAM',
    shortLabel: 'Lap VAM',
    description: 'VAM for current lap',
    category: 'elevation',
    unit: 'm/h',
    unitImperial: 'ft/h',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'trending-up',
  },

  // ---------------------------------------------------------------------------
  // NAVIGATION WIDGETS
  // ---------------------------------------------------------------------------
  heading: {
    type: 'heading',
    label: 'Heading',
    shortLabel: 'Heading',
    description: 'Current compass heading',
    category: 'navigation',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'navigation',
  },
  bearing: {
    type: 'bearing',
    label: 'Bearing',
    shortLabel: 'Bearing',
    description: 'Bearing to destination',
    category: 'navigation',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'navigation',
  },
  course_point_distance: {
    type: 'course_point_distance',
    label: 'To Course Point',
    shortLabel: 'To CP',
    description: 'Distance to next course point',
    category: 'navigation',
    unit: 'km',
    unitImperial: 'mi',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'navigation',
  },
  course_point_name: {
    type: 'course_point_name',
    label: 'Course Point',
    shortLabel: 'CP Name',
    description: 'Name of next course point',
    category: 'navigation',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 2,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'navigation',
  },
  turn_distance: {
    type: 'turn_distance',
    label: 'Turn Distance',
    shortLabel: 'Turn In',
    description: 'Distance to next turn',
    category: 'navigation',
    unit: 'm',
    unitImperial: 'ft',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'navigation',
  },
  turn_direction: {
    type: 'turn_direction',
    label: 'Turn Direction',
    shortLabel: 'Turn',
    description: 'Direction of next turn',
    category: 'navigation',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'navigation',
  },
  off_course: {
    type: 'off_course',
    label: 'Off Course',
    shortLabel: 'Off Crs',
    description: 'Distance off planned route',
    category: 'navigation',
    unit: 'm',
    unitImperial: 'ft',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'navigation',
  },
  gps_accuracy: {
    type: 'gps_accuracy',
    label: 'GPS Accuracy',
    shortLabel: 'GPS Acc',
    description: 'Current GPS accuracy',
    category: 'navigation',
    unit: 'm',
    unitImperial: 'ft',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'navigation',
  },
  gps_signal: {
    type: 'gps_signal',
    label: 'GPS Signal',
    shortLabel: 'GPS',
    description: 'GPS signal strength indicator',
    category: 'navigation',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresGPS: true,
    icon: 'navigation',
  },

  // ---------------------------------------------------------------------------
  // PERFORMANCE WIDGETS
  // ---------------------------------------------------------------------------
  calories: {
    type: 'calories',
    label: 'Calories',
    shortLabel: 'Cal',
    description: 'Calories burned',
    category: 'performance',
    unit: 'kcal',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'activity',
  },
  calories_remaining: {
    type: 'calories_remaining',
    label: 'Calories Remaining',
    shortLabel: 'Cal Rem',
    description: 'Calories remaining in target',
    category: 'performance',
    unit: 'kcal',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'activity',
  },
  kilojoules: {
    type: 'kilojoules',
    label: 'Kilojoules',
    shortLabel: 'kJ',
    description: 'Work done in kilojoules',
    category: 'performance',
    unit: 'kJ',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'activity',
  },
  tss: {
    type: 'tss',
    label: 'TSS',
    shortLabel: 'TSS',
    description: 'Training Stress Score',
    category: 'performance',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'activity',
  },
  training_load: {
    type: 'training_load',
    label: 'Training Load',
    shortLabel: 'Load',
    description: 'Current training load',
    category: 'performance',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'activity',
  },
  performance_condition: {
    type: 'performance_condition',
    label: 'Performance',
    shortLabel: 'Perf',
    description: 'Real-time performance assessment',
    category: 'performance',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'activity',
  },
  stamina: {
    type: 'stamina',
    label: 'Stamina',
    shortLabel: 'Stamina',
    description: 'Current stamina remaining',
    category: 'performance',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'activity',
  },
  stamina_potential: {
    type: 'stamina_potential',
    label: 'Potential Stamina',
    shortLabel: 'Pot Stam',
    description: 'Potential stamina if fully recovered',
    category: 'performance',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'activity',
  },
  aerobic_te: {
    type: 'aerobic_te',
    label: 'Aerobic TE',
    shortLabel: 'Aer TE',
    description: 'Aerobic Training Effect',
    category: 'performance',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    icon: 'activity',
  },
  anaerobic_te: {
    type: 'anaerobic_te',
    label: 'Anaerobic TE',
    shortLabel: 'Ana TE',
    description: 'Anaerobic Training Effect',
    category: 'performance',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    icon: 'activity',
  },

  // ---------------------------------------------------------------------------
  // GEAR WIDGETS
  // ---------------------------------------------------------------------------
  gear: {
    type: 'gear',
    label: 'Gear',
    shortLabel: 'Gear',
    description: 'Current gear selection',
    category: 'gears',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'sram_axs',
    icon: 'settings',
  },
  gear_front: {
    type: 'gear_front',
    label: 'Front Gear',
    shortLabel: 'Front',
    description: 'Front chainring position',
    category: 'gears',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'sram_axs',
    icon: 'settings',
  },
  gear_rear: {
    type: 'gear_rear',
    label: 'Rear Gear',
    shortLabel: 'Rear',
    description: 'Rear cassette position',
    category: 'gears',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'sram_axs',
    icon: 'settings',
  },
  gear_ratio: {
    type: 'gear_ratio',
    label: 'Gear Ratio',
    shortLabel: 'Ratio',
    description: 'Current gear ratio',
    category: 'gears',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'sram_axs',
    icon: 'settings',
  },
  gear_combo: {
    type: 'gear_combo',
    label: 'Gear Combo',
    shortLabel: 'Combo',
    description: 'Front/rear gear combination',
    category: 'gears',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'sram_axs',
    icon: 'settings',
  },
  gear_battery: {
    type: 'gear_battery',
    label: 'Shifter Battery',
    shortLabel: 'Shft Bat',
    description: 'Electronic shifter battery level',
    category: 'gears',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'sram_axs',
    icon: 'settings',
  },
  di2_battery: {
    type: 'di2_battery',
    label: 'Di2 Battery',
    shortLabel: 'Di2 Bat',
    description: 'Shimano Di2 battery level',
    category: 'gears',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'shimano_di2',
    icon: 'settings',
  },

  // ---------------------------------------------------------------------------
  // ENVIRONMENT WIDGETS
  // ---------------------------------------------------------------------------
  temperature: {
    type: 'temperature',
    label: 'Temperature',
    shortLabel: 'Temp',
    description: 'Current temperature',
    category: 'environment',
    unit: '°C',
    unitImperial: '°F',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'sun',
  },
  humidity: {
    type: 'humidity',
    label: 'Humidity',
    shortLabel: 'Humid',
    description: 'Current humidity',
    category: 'environment',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'sun',
  },
  wind_speed: {
    type: 'wind_speed',
    label: 'Wind Speed',
    shortLabel: 'Wind',
    description: 'Current wind speed',
    category: 'environment',
    unit: 'km/h',
    unitImperial: 'mph',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'sun',
  },
  wind_direction: {
    type: 'wind_direction',
    label: 'Wind Direction',
    shortLabel: 'Wind Dir',
    description: 'Current wind direction',
    category: 'environment',
    unit: '',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'sun',
  },
  weather: {
    type: 'weather',
    label: 'Weather',
    shortLabel: 'Weather',
    description: 'Current weather conditions',
    category: 'environment',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 2,
    defaultHeight: 1,
    icon: 'sun',
  },
  battery_level: {
    type: 'battery_level',
    label: 'Device Battery',
    shortLabel: 'Battery',
    description: 'Device battery level',
    category: 'environment',
    unit: '%',
    minWidth: 1,
    minHeight: 1,
    defaultWidth: 1,
    defaultHeight: 1,
    icon: 'sun',
  },

  // ---------------------------------------------------------------------------
  // GRAPH WIDGETS
  // ---------------------------------------------------------------------------
  graph_power: {
    type: 'graph_power',
    label: 'Power Graph',
    shortLabel: 'Pwr Graph',
    description: 'Power output over time',
    category: 'graphs',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 3,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'power',
    supportsGraph: true,
    icon: 'bar-chart',
  },
  graph_heart_rate: {
    type: 'graph_heart_rate',
    label: 'HR Graph',
    shortLabel: 'HR Graph',
    description: 'Heart rate over time',
    category: 'graphs',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 3,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'heart_rate',
    supportsGraph: true,
    icon: 'bar-chart',
  },
  graph_speed: {
    type: 'graph_speed',
    label: 'Speed Graph',
    shortLabel: 'Spd Graph',
    description: 'Speed over time',
    category: 'graphs',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 3,
    defaultHeight: 1,
    requiresGPS: true,
    supportsGraph: true,
    icon: 'bar-chart',
  },
  graph_elevation: {
    type: 'graph_elevation',
    label: 'Elevation Graph',
    shortLabel: 'Elev Graph',
    description: 'Elevation profile over distance',
    category: 'graphs',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 3,
    defaultHeight: 1,
    requiresGPS: true,
    supportsGraph: true,
    icon: 'bar-chart',
  },
  graph_cadence: {
    type: 'graph_cadence',
    label: 'Cadence Graph',
    shortLabel: 'Cad Graph',
    description: 'Cadence over time',
    category: 'graphs',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 3,
    defaultHeight: 1,
    requiresSensor: true,
    sensorType: 'cadence',
    supportsGraph: true,
    icon: 'bar-chart',
  },
  graph_grade: {
    type: 'graph_grade',
    label: 'Grade Graph',
    shortLabel: 'Grd Graph',
    description: 'Gradient over distance',
    category: 'graphs',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 3,
    defaultHeight: 1,
    requiresGPS: true,
    supportsGraph: true,
    icon: 'bar-chart',
  },

  // ---------------------------------------------------------------------------
  // MAP WIDGETS
  // ---------------------------------------------------------------------------
  map: {
    type: 'map',
    label: 'Map',
    shortLabel: 'Map',
    description: 'Full navigation map',
    category: 'maps',
    unit: '',
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 3,
    defaultHeight: 3,
    requiresGPS: true,
    icon: 'map',
  },
  map_mini: {
    type: 'map_mini',
    label: 'Mini Map',
    shortLabel: 'Mini Map',
    description: 'Compact map view',
    category: 'maps',
    unit: '',
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 2,
    defaultHeight: 2,
    requiresGPS: true,
    icon: 'map',
  },
  climb_profile: {
    type: 'climb_profile',
    label: 'Climb Profile',
    shortLabel: 'Climb',
    description: 'Current climb visualization with gradient',
    category: 'maps',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 3,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'map',
  },
  elevation_profile: {
    type: 'elevation_profile',
    label: 'Elevation Profile',
    shortLabel: 'Elev Prof',
    description: 'Route elevation profile',
    category: 'maps',
    unit: '',
    minWidth: 2,
    minHeight: 1,
    defaultWidth: 3,
    defaultHeight: 1,
    requiresRoute: true,
    icon: 'map',
  },
  route_preview: {
    type: 'route_preview',
    label: 'Route Preview',
    shortLabel: 'Route',
    description: 'Overview of planned route',
    category: 'maps',
    unit: '',
    minWidth: 2,
    minHeight: 2,
    defaultWidth: 2,
    defaultHeight: 2,
    requiresRoute: true,
    icon: 'map',
  },
};

// =============================================================================
// HELPER FUNCTIONS
// =============================================================================

export function getWidgetsByCategory(category: WidgetCategory): WidgetDefinition[] {
  return Object.values(WIDGET_DEFINITIONS).filter((w) => w.category === category);
}

export function getWidgetsRequiringSensor(sensorType: string): WidgetDefinition[] {
  return Object.values(WIDGET_DEFINITIONS).filter(
    (w) => w.requiresSensor && w.sensorType === sensorType
  );
}

export function getWidgetsRequiringGPS(): WidgetDefinition[] {
  return Object.values(WIDGET_DEFINITIONS).filter((w) => w.requiresGPS);
}

export function getWidgetsRequiringRoute(): WidgetDefinition[] {
  return Object.values(WIDGET_DEFINITIONS).filter((w) => w.requiresRoute);
}

// =============================================================================
// GRID CONFIGURATION
// =============================================================================

export const DATA_SCREEN_GRID = {
  columns: 3,
  rows: 4,
} as const;

// =============================================================================
// DEFAULT SCREEN LAYOUTS BY USE CASE
// =============================================================================

export interface DefaultScreenLayout {
  profile: ScreenProfile;
  name: string;
  description: string;
  screenType: 'data' | 'map' | 'climb';
  widgets: Widget[];
}

export const DEFAULT_SCREEN_LAYOUTS: DefaultScreenLayout[] = [
  // ---------------------------------------------------------------------------
  // ROAD RACING - Power-focused for competitive riding
  // ---------------------------------------------------------------------------
  {
    profile: 'road_racing',
    name: 'Road Racing',
    description: 'Power-focused layout for competitive road cycling and racing',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'power_3s', x: 0, y: 0, width: 1, height: 1 },
      { id: 'w2', type: 'heart_rate', x: 1, y: 0, width: 1, height: 1 },
      { id: 'w3', type: 'speed', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'power_normalized', x: 0, y: 1, width: 1, height: 1 },
      { id: 'w5', type: 'time_elapsed', x: 1, y: 1, width: 1, height: 1 },
      { id: 'w6', type: 'distance', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w7', type: 'cadence', x: 0, y: 2, width: 1, height: 1 },
      { id: 'w8', type: 'power_if', x: 1, y: 2, width: 1, height: 1 },
      { id: 'w9', type: 'tss', x: 2, y: 2, width: 1, height: 1 },
      { id: 'w10', type: 'power_avg', x: 0, y: 3, width: 1, height: 1 },
      { id: 'w11', type: 'speed_avg', x: 1, y: 3, width: 1, height: 1 },
      { id: 'w12', type: 'time_of_day', x: 2, y: 3, width: 1, height: 1 },
    ],
  },

  // ---------------------------------------------------------------------------
  // CLIMBING - Elevation and pacing focused
  // ---------------------------------------------------------------------------
  {
    profile: 'climbing',
    name: 'Climbing',
    description: 'Optimized for hill climbs with elevation and VAM metrics',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'grade', x: 0, y: 0, width: 1, height: 1 },
      { id: 'w2', type: 'power_3s', x: 1, y: 0, width: 1, height: 1 },
      { id: 'w3', type: 'heart_rate', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'vam', x: 0, y: 1, width: 1, height: 1 },
      { id: 'w5', type: 'elevation_gain', x: 1, y: 1, width: 1, height: 1 },
      { id: 'w6', type: 'elevation', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w7', type: 'speed', x: 0, y: 2, width: 1, height: 1 },
      { id: 'w8', type: 'cadence', x: 1, y: 2, width: 1, height: 1 },
      { id: 'w9', type: 'distance', x: 2, y: 2, width: 1, height: 1 },
      { id: 'w10', type: 'power_per_kg', x: 0, y: 3, width: 1, height: 1 },
      { id: 'w11', type: 'time_elapsed', x: 1, y: 3, width: 1, height: 1 },
      { id: 'w12', type: 'elevation_remaining', x: 2, y: 3, width: 1, height: 1 },
    ],
  },

  // ---------------------------------------------------------------------------
  // STRUCTURED TRAINING - Intervals and workout targets
  // ---------------------------------------------------------------------------
  {
    profile: 'training',
    name: 'Structured Training',
    description: 'For interval training with lap metrics and zone tracking',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'power_3s', x: 0, y: 0, width: 1, height: 1 },
      { id: 'w2', type: 'power_zone', x: 1, y: 0, width: 1, height: 1 },
      { id: 'w3', type: 'heart_rate_zone', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'time_lap', x: 0, y: 1, width: 1, height: 1 },
      { id: 'w5', type: 'power_lap', x: 1, y: 1, width: 1, height: 1 },
      { id: 'w6', type: 'heart_rate_lap', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w7', type: 'laps', x: 0, y: 2, width: 1, height: 1 },
      { id: 'w8', type: 'cadence', x: 1, y: 2, width: 1, height: 1 },
      { id: 'w9', type: 'tss', x: 2, y: 2, width: 1, height: 1 },
      { id: 'w10', type: 'time_elapsed', x: 0, y: 3, width: 1, height: 1 },
      { id: 'w11', type: 'power_avg', x: 1, y: 3, width: 1, height: 1 },
      { id: 'w12', type: 'kilojoules', x: 2, y: 3, width: 1, height: 1 },
    ],
  },

  // ---------------------------------------------------------------------------
  // ENDURANCE - Long ride essentials
  // ---------------------------------------------------------------------------
  {
    profile: 'endurance',
    name: 'Endurance',
    description: 'Essential metrics for long-distance rides',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'speed', x: 0, y: 0, width: 1, height: 1 },
      { id: 'w2', type: 'heart_rate', x: 1, y: 0, width: 1, height: 1 },
      { id: 'w3', type: 'cadence', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'time_elapsed', x: 0, y: 1, width: 1, height: 1 },
      { id: 'w5', type: 'distance', x: 1, y: 1, width: 1, height: 1 },
      { id: 'w6', type: 'elevation_gain', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w7', type: 'speed_avg', x: 0, y: 2, width: 1, height: 1 },
      { id: 'w8', type: 'heart_rate_avg', x: 1, y: 2, width: 1, height: 1 },
      { id: 'w9', type: 'calories', x: 2, y: 2, width: 1, height: 1 },
      { id: 'w10', type: 'time_of_day', x: 0, y: 3, width: 1, height: 1 },
      { id: 'w11', type: 'time_moving', x: 1, y: 3, width: 1, height: 1 },
      { id: 'w12', type: 'battery_level', x: 2, y: 3, width: 1, height: 1 },
    ],
  },

  // ---------------------------------------------------------------------------
  // NAVIGATION - Route following focused
  // ---------------------------------------------------------------------------
  {
    profile: 'navigation',
    name: 'Navigation',
    description: 'Map-focused layout for route following',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'turn_distance', x: 0, y: 0, width: 1, height: 1 },
      { id: 'w2', type: 'turn_direction', x: 1, y: 0, width: 1, height: 1 },
      { id: 'w3', type: 'distance_remaining', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'map_mini', x: 0, y: 1, width: 2, height: 2 },
      { id: 'w5', type: 'time_eta', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w6', type: 'elevation_remaining', x: 2, y: 2, width: 1, height: 1 },
      { id: 'w7', type: 'speed', x: 0, y: 3, width: 1, height: 1 },
      { id: 'w8', type: 'distance', x: 1, y: 3, width: 1, height: 1 },
      { id: 'w9', type: 'time_of_day', x: 2, y: 3, width: 1, height: 1 },
    ],
  },

  // ---------------------------------------------------------------------------
  // INDOOR TRAINING - Smart trainer focused
  // ---------------------------------------------------------------------------
  {
    profile: 'indoor',
    name: 'Indoor Training',
    description: 'Optimized for smart trainer and indoor sessions',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'power_3s', x: 0, y: 0, width: 1, height: 1 },
      { id: 'w2', type: 'heart_rate', x: 1, y: 0, width: 1, height: 1 },
      { id: 'w3', type: 'cadence', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'power_zone', x: 0, y: 1, width: 1, height: 1 },
      { id: 'w5', type: 'time_elapsed', x: 1, y: 1, width: 1, height: 1 },
      { id: 'w6', type: 'heart_rate_zone', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w7', type: 'power_avg', x: 0, y: 2, width: 1, height: 1 },
      { id: 'w8', type: 'power_normalized', x: 1, y: 2, width: 1, height: 1 },
      { id: 'w9', type: 'kilojoules', x: 2, y: 2, width: 1, height: 1 },
      { id: 'w10', type: 'power_ftp_percent', x: 0, y: 3, width: 1, height: 1 },
      { id: 'w11', type: 'tss', x: 1, y: 3, width: 1, height: 1 },
      { id: 'w12', type: 'calories', x: 2, y: 3, width: 1, height: 1 },
    ],
  },

  // ---------------------------------------------------------------------------
  // MTB - Mountain biking focused
  // ---------------------------------------------------------------------------
  {
    profile: 'mtb',
    name: 'Mountain Bike',
    description: 'Trail riding with elevation and gear info',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'speed', x: 0, y: 0, width: 1, height: 1 },
      { id: 'w2', type: 'grade', x: 1, y: 0, width: 1, height: 1 },
      { id: 'w3', type: 'heart_rate', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'elevation', x: 0, y: 1, width: 1, height: 1 },
      { id: 'w5', type: 'elevation_gain', x: 1, y: 1, width: 1, height: 1 },
      { id: 'w6', type: 'gear', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w7', type: 'distance', x: 0, y: 2, width: 1, height: 1 },
      { id: 'w8', type: 'time_elapsed', x: 1, y: 2, width: 1, height: 1 },
      { id: 'w9', type: 'cadence', x: 2, y: 2, width: 1, height: 1 },
      { id: 'w10', type: 'speed_max', x: 0, y: 3, width: 1, height: 1 },
      { id: 'w11', type: 'elevation_loss', x: 1, y: 3, width: 1, height: 1 },
      { id: 'w12', type: 'time_of_day', x: 2, y: 3, width: 1, height: 1 },
    ],
  },

  // ---------------------------------------------------------------------------
  // GRAVEL - Mix of navigation and performance
  // ---------------------------------------------------------------------------
  {
    profile: 'gravel',
    name: 'Gravel',
    description: 'Balanced layout for gravel and adventure riding',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'speed', x: 0, y: 0, width: 1, height: 1 },
      { id: 'w2', type: 'heart_rate', x: 1, y: 0, width: 1, height: 1 },
      { id: 'w3', type: 'distance_remaining', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'elevation_gain', x: 0, y: 1, width: 1, height: 1 },
      { id: 'w5', type: 'grade', x: 1, y: 1, width: 1, height: 1 },
      { id: 'w6', type: 'elevation_remaining', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w7', type: 'distance', x: 0, y: 2, width: 1, height: 1 },
      { id: 'w8', type: 'time_elapsed', x: 1, y: 2, width: 1, height: 1 },
      { id: 'w9', type: 'time_eta', x: 2, y: 2, width: 1, height: 1 },
      { id: 'w10', type: 'cadence', x: 0, y: 3, width: 1, height: 1 },
      { id: 'w11', type: 'calories', x: 1, y: 3, width: 1, height: 1 },
      { id: 'w12', type: 'battery_level', x: 2, y: 3, width: 1, height: 1 },
    ],
  },

  // ---------------------------------------------------------------------------
  // COMMUTE - Simple everyday riding
  // ---------------------------------------------------------------------------
  {
    profile: 'commute',
    name: 'Commute',
    description: 'Simple layout for daily commuting',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'speed', x: 0, y: 0, width: 1, height: 1 },
      { id: 'w2', type: 'time_of_day', x: 1, y: 0, width: 1, height: 1 },
      { id: 'w3', type: 'time_eta', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'distance', x: 0, y: 1, width: 1, height: 1 },
      { id: 'w5', type: 'time_elapsed', x: 1, y: 1, width: 1, height: 1 },
      { id: 'w6', type: 'distance_remaining', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w7', type: 'map_mini', x: 0, y: 2, width: 2, height: 2 },
      { id: 'w8', type: 'turn_distance', x: 2, y: 2, width: 1, height: 1 },
      { id: 'w9', type: 'battery_level', x: 2, y: 3, width: 1, height: 1 },
    ],
  },

  // ---------------------------------------------------------------------------
  // MINIMAL - Clean, distraction-free
  // ---------------------------------------------------------------------------
  {
    profile: 'minimal',
    name: 'Minimal',
    description: 'Clean layout with essential metrics only',
    screenType: 'data',
    widgets: [
      { id: 'w1', type: 'speed', x: 0, y: 0, width: 1, height: 2 },
      { id: 'w2', type: 'heart_rate', x: 1, y: 0, width: 1, height: 2 },
      { id: 'w3', type: 'time_elapsed', x: 2, y: 0, width: 1, height: 1 },
      { id: 'w4', type: 'distance', x: 2, y: 1, width: 1, height: 1 },
      { id: 'w5', type: 'elevation_gain', x: 0, y: 2, width: 1, height: 1 },
      { id: 'w6', type: 'cadence', x: 1, y: 2, width: 1, height: 1 },
      { id: 'w7', type: 'time_of_day', x: 2, y: 2, width: 1, height: 1 },
    ],
  },
];

// Legacy default layout for backwards compatibility
export const DEFAULT_DATA_LAYOUT = {
  name: 'Default',
  screenType: 'data' as const,
  widgets: DEFAULT_SCREEN_LAYOUTS[3].widgets, // Endurance profile
  isActive: true,
};

// =============================================================================
// LCD COLOR PALETTE
// =============================================================================

export const LCD_COLORS = {
  background: '#e5e5e0',
  text: '#222222',
  textSecondary: '#666666',
  border: '#999999',
  accentBlue: '#0066cc',
  accentGreen: '#22c55e',
  accentRed: '#ef4444',
  accentOrange: '#f59e0b',
  accentPurple: '#8b5cf6',
} as const;

// =============================================================================
// ZONE COLOR SCALES
// =============================================================================

export const POWER_ZONE_COLORS = {
  1: '#9ca3af', // Recovery - Gray
  2: '#3b82f6', // Endurance - Blue
  3: '#22c55e', // Tempo - Green
  4: '#f59e0b', // Threshold - Orange
  5: '#ef4444', // VO2max - Red
  6: '#dc2626', // Anaerobic - Dark Red
  7: '#7c2d12', // Neuromuscular - Brown
} as const;

export const HEART_RATE_ZONE_COLORS = {
  1: '#9ca3af', // Zone 1 - Gray
  2: '#3b82f6', // Zone 2 - Blue
  3: '#22c55e', // Zone 3 - Green
  4: '#f59e0b', // Zone 4 - Orange
  5: '#ef4444', // Zone 5 - Red
} as const;
